name: QA Environment - Scheduled Tests

on:
  schedule:
    # Runs every day at 8:00 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  test:
    name: Run API Tests - QA
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test
        env:
          BASE_URL: https://petstore.swagger.io
          API_VERSION: /v2

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-qa
          path: playwright-report/
          retention-days: 30

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-qa
          path: test-results/
          retention-days: 30
